sources:
  - id: desktops
    name: "Настольные компьютеры"
    url: "https://www.avito.ru/rostov-na-donu/nastolnye_kompyutery?context=H4sIAAAAAAAA_wEmANn_YToxOntzOjE6InkiO3M6MTY6IlM1UEJlQmpzQ1pNdWJpSzciO31M4J4OJgAAAA&localPriority=0&s=104"
